name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 21
    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew build

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: DingusPPC-MSBUILD
        path: .



